/**
 * ═══════════════════════════════════════════════════════════════════════════
 * LUMIX / BOOKME — CUSTOM ICON CONFIGURATION MAPPING
 * ═══════════════════════════════════════════════════════════════════════════
 * 
 * Instructions:
 * 1. To map an icon to a custom SVG in `frontend/public/`, set its value
 *    to the filename (e.g., 'ticket-sale-svgrepo-com.svg').
 * 2. To use the default Lucide SVG icon, leave its value as `null` or `''`.
 * 3. Whenever you modify this file, tell the assistant to build it, or run:
 *    `node scripts/build_icons.js`
 */

export const ICON_MAP = {
  // ─── CURRENTLY MAPPED CUSTOM SVGS ───
  Ticket: 'ticket-sale-svgrepo-com.svg',
  Calendar: 'calender-svgrepo-com.svg',
  BarChart3: 'chart-bar-alt-square-svgrepo-com.svg',
  Clock: 'clock-circle-svgrepo-com.svg',
  LayoutDashboard: 'dashboard-svgrepo-com (1).svg',
  DollarSign: 'dollar-circle-svgrepo-com.svg',
  Filter: 'filter-svgrepo-com.svg',
  Info: 'info-circle-svgrepo-com.svg',
  LogOut: 'logout-svgrepo-com.svg',
  Moon: 'moon-svgrepo-com.svg',
  Sun: 'sun-svgrepo-com.svg',
  Film: 'movie-film-roll-for-movie-svgrepo-com.svg',
  Percent: 'percent-circle-svgrepo-com.svg',
  PieChart: 'pie-chart-2-svgrepo-com.svg',
  Save: 'save-svgrepo-com.svg',
  Search: 'search-alt-2-svgrepo-com.svg',
  Settings: 'settings-svgrepo-com.svg',
  Volume2: 'speaker-wave-1-svgrepo-com.svg',
  Flame: 'fire-svgrepo-com.svg',
  Star: 'star-svgrepo-com.svg',
  MapPin: 'location-svgrepo-com.svg',
  Play: 'play-svgrepo-com.svg',
  Shield: 'shield-minimalistic-svgrepo-com.svg',
  ShieldCheck: 'shield-minimalistic-svgrepo-com.svg',
  CinemaIcon: 'cinema-film-movies-add-svgrepo-com.svg',
  StadiumIcon: 'stadium-svgrepo-com.svg',
  TheatreIcon: 'drama-masks-svgrepo-com.svg',
  Bell: 'bell-svgrepo-com.svg',

  // ─── WEBSITE ICONS WITH DEFAULT FALLBACK (SET FILENAME TO OVERRIDE) ───
  Activity: null,
  AlertCircle: null,
  AlertTriangle: null,
  Armchair: null,
  ArrowLeft: null,
  ArrowRight: null,
  ArrowUpRight: null,
  Building2: null,
  Camera: null,
  Check: null,
  CheckCircle2: null,
  ChevronDown: null,
  ChevronLeft: null,
  ChevronRight: null,
  ChevronUp: null,
  Compass: null,
  Copy: null,
  CornerUpLeft: null,
  CornerUpRight: null,
  CreditCard: null,
  Disc: null,
  Download: null,
  Edit3: null,
  ExternalLink: null,
  Eye: null,
  EyeOff: null,
  FileText: null,
  Flag: null,
  Globe: null,
  Globe2: null,
  Grid: null,
  Hash: null,
  HelpCircle: null,
  KeyRound: null,
  Layers: null,
  LayoutGrid: null,
  Loader2: null,
  Lock: null,
  Mail: null,
  Map: null,
  Maximize2: null,
  Menu: null,
  MessageSquare: null,
  Mic: null,
  Minus: null,
  MousePointer: null,
  Move: null,
  Music: null,
  Navigation: null,
  PenTool: null,
  Plus: null,
  QrCode: null,
  RotateCw: null,
  Slash: null,
  Sliders: null,
  SlidersHorizontal: null,
  Sparkles: null,
  Square: null,
  Swords: null,
  Trash2: null,
  TrendingUp: null,
  Trophy: null,
  Tv: null,
  Type: null,
  Upload: null,
  User: null,
  UserCheck: null,
  Users: null,
  Wand2: null,
  X: null,
  ZoomIn: null,
  ZoomOut: null,
};
